### ISSUE TITLE
Created a new project, but do not see sonar.gitlab.user_token in project settings?

### ISSUE THREAD

**Issue by CptanPanic** [gabrie-allaigre/sonar-gitlab-plugin#89]
The docs say that I should be able to set sonar.gitlab.user_token on a per project basis, but I do not see this option under project settings.  Only project id, and max issue gates.  Is this possible?

**Comment by gabrie-allaigre** [comment]
Hi,
Use command line for change user_token `-Dsonar.gitlab.user_token=12346`

**Comment by morpheus9999** [comment]
Can you fix this?
I don't want to use command line inside Jenkins pipeline to change user_token.
If possible please support overriding sonar.gitlab.user_token inside project settings.

**Comment by morpheus9999** [comment]
@gabrie-allaigre Can you check the PR?

**Comment by gabrie-allaigre** [comment]
Hi, I'm on vacations. I will look next week.

**Comment by vuza** [comment]
For me the option now is available at the Plug-in Settings, but it has no affect. When I provide the Gitlab User Token in the CLI everything works, when I provide it in the Plug-in Settings, it does not. sonarqube than does not have access to the repository, because it cannot read the Plug-in leben User Token I assume.

Can anybody 100% confirm that setting the Gitlab User Token in the Plug-in Settings only and not providing in through the CLI works for him?

Any other ideas? Every help very much appreciated.
